"""Load synthetic_wells.csv + synthetic_water_samples.csv into the DB.

Each synthetic well goes into monitoring_wells; each synthetic sample lands
in water_samples with synthetic=True. A `data_sources` row of type
`synthetic_copula` links every inserted record so they can be wiped easily:

    DELETE FROM water_samples WHERE source_id IN (
        SELECT id FROM data_sources WHERE source_type='synthetic_copula'
    );

Run:
    cd backend
    python -m ml.synthetic         # creates fakedataset/*.csv first
    python -m ml.load_synthetic    # then ingests into DB
"""
from __future__ import annotations

import argparse
import asyncio
import hashlib
import uuid
from datetime import datetime, timezone
from pathlib import Path

import pandas as pd
from loguru import logger
from sqlalchemy import select, text

from app.database import AsyncSessionLocal
from app.models.data_source import DataSource
from app.models.monitoring_well import MonitoringWell
from app.models.water_sample import WaterSample
from ml import FAKEDATASET_DIR


SAMPLE_NUMERIC_COLS = [
    "ph", "ec_us_cm", "tds_mg_l", "turbidity_ntu", "do_mg_l", "total_hardness",
    "uranium_ppb", "nitrate_mg_l", "fluoride_mg_l", "arsenic_ppb", "iron_ppm",
    "chloride_mg_l", "sulphate_mg_l", "bicarbonate_mg_l", "carbonate_mg_l",
    "phosphate_mg_l", "calcium_mg_l", "magnesium_mg_l", "sodium_mg_l", "potassium_mg_l",
]


async def _get_or_create_source(session, checksum: str) -> uuid.UUID:
    existing = await session.execute(
        select(DataSource).where(
            DataSource.name == "synthetic_water_samples_v1",
            DataSource.checksum == checksum,
        )
    )
    obj = existing.scalar_one_or_none()
    if obj:
        return obj.id

    obj = DataSource(
        name="synthetic_water_samples_v1",
        source_type="synthetic_copula",
        file_name="synthetic_water_samples.csv",
        checksum=checksum,
        loaded_at=datetime.now(timezone.utc),
        notes="Generated by ml.synthetic.GaussianCopulaGenerator (Month 4 augmentation)",
    )
    session.add(obj)
    await session.flush()
    return obj.id


async def _upsert_wells(session, wells_df: pd.DataFrame, source_id: uuid.UUID) -> dict:
    """Insert or fetch wells. Returns {well_name: well_id}."""
    name_to_id: dict = {}
    for _, row in wells_df.iterrows():
        existing = await session.execute(
            select(MonitoringWell).where(
                MonitoringWell.latitude == float(row["latitude"]),
                MonitoringWell.longitude == float(row["longitude"]),
            )
        )
        well = existing.scalar_one_or_none()
        if well:
            name_to_id[row["name"]] = well.id
            continue

        well = MonitoringWell(
            name=row["name"],
            latitude=float(row["latitude"]),
            longitude=float(row["longitude"]),
            location=text(
                f"ST_SetSRID(ST_MakePoint({float(row['longitude'])}, {float(row['latitude'])}), 4326)"
            ),
            depth=float(row["depth"]) if pd.notna(row["depth"]) else None,
            well_type=row.get("well_type"),
            source_id=source_id,
        )
        session.add(well)
        await session.flush()
        name_to_id[row["name"]] = well.id
    return name_to_id


async def _insert_samples(
    session, samples_df: pd.DataFrame, name_to_id: dict, source_id: uuid.UUID
) -> int:
    inserted = 0
    for _, row in samples_df.iterrows():
        well_id = name_to_id.get(row["well_name"])
        if not well_id:
            continue
        kwargs = {"well_id": well_id, "source_id": source_id, "synthetic": True}
        sampled_at = row.get("sampled_at")
        try:
            kwargs["sampled_at"] = pd.to_datetime(sampled_at).to_pydatetime()
        except Exception:
            kwargs["sampled_at"] = datetime.now(timezone.utc)
        for col in SAMPLE_NUMERIC_COLS:
            v = row.get(col)
            kwargs[col] = float(v) if pd.notna(v) else None
        session.add(WaterSample(**kwargs))
        inserted += 1
        if inserted % 100 == 0:
            await session.flush()
    await session.flush()
    return inserted


async def load(
    wells_path: Path | None = None,
    samples_path: Path | None = None,
) -> dict:
    wells_path = wells_path or (FAKEDATASET_DIR / "synthetic_wells.csv")
    samples_path = samples_path or (FAKEDATASET_DIR / "synthetic_water_samples.csv")

    if not wells_path.exists() or not samples_path.exists():
        raise FileNotFoundError(
            f"Run `python -m ml.synthetic` first; expected {wells_path} and {samples_path}"
        )

    wells_df = pd.read_csv(wells_path)
    samples_df = pd.read_csv(samples_path)

    # checksum based on file bytes (idempotent re-runs are deduped)
    checksum = hashlib.sha256(samples_path.read_bytes()).hexdigest()

    async with AsyncSessionLocal() as session:
        source_id = await _get_or_create_source(session, checksum)
        name_to_id = await _upsert_wells(session, wells_df, source_id)
        inserted = await _insert_samples(session, samples_df, name_to_id, source_id)
        await session.commit()

    summary = {
        "wells_referenced": len(name_to_id),
        "samples_inserted": inserted,
        "source_id": str(source_id),
    }
    logger.info(f"Synthetic load complete: {summary}")
    return summary


def _cli() -> None:
    parser = argparse.ArgumentParser()
    parser.add_argument("--wells-path", type=Path, default=None)
    parser.add_argument("--samples-path", type=Path, default=None)
    args = parser.parse_args()
    asyncio.run(load(wells_path=args.wells_path, samples_path=args.samples_path))


if __name__ == "__main__":
    _cli()
