"""Month 4: add synthetic flag to water_samples for ML augmentation tracking."""
from alembic import op
import sqlalchemy as sa

revision = '0005_water_samples_synth'
down_revision = '0004_month3_schema'
branch_labels = None
depends_on = None


def upgrade() -> None:
    op.add_column(
        'water_samples',
        sa.Column(
            'synthetic',
            sa.Boolean(),
            nullable=False,
            server_default=sa.text('false'),
            comment='True for samples generated by ml.synthetic.GaussianCopulaGenerator',
        ),
    )
    op.create_index('ix_water_samples_synthetic', 'water_samples', ['synthetic'])


def downgrade() -> None:
    op.drop_index('ix_water_samples_synthetic', table_name='water_samples')
    op.drop_column('water_samples', 'synthetic')
